[project]
name = "emotion-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepface>=0.0.93",
    "matplotlib>=3.10.3",
    "numpy==1.24.4",
    "pip>=25.1.1",
]
